### ISSUE TITLE
Currying?

### ISSUE THREAD

**Issue by kevinSuttle** [mindeavor/es-papp#3]
Forgive my ignorance, but isn't "partial application" the same thing as "currying"? http://javascript.crockford.com/www_svendtofte_com/code/curried_javascript/

**Comment by stylemistake** [comment]
I had the same question some days ago, when I first seen this.

Technically it isn't currying, because currying is a creation of a function, where partial application outputs a function with remaining arguments, which can be called, and its output can be called, until all arguments are applied. In javascript, this would look like this:

```js
const fn = (a, b, c) => a + b + c;

const curried = fn.curry();
curried(a)(b)(c); // 6

const uncurried = curriedFn.uncurry();
uncurried(1, 2, 3); // 6
```

And what author of this repository proposes, is the **actual** and explicit partial application, which isn't currying.

But I must admit - `papp` is a very bad name, and I see why we would want to call it `curry` instead.

**Comment by mindeavor** [comment]
@stylemistake is correct; currying is making a function only ever take one argument. You can write curried functions today quite easily in JS:

```js
// currying!
var add = (x) => (y) => x + y

var result = add(10)(15)
result //=> 25
```

@stylemistake Be careful about how you express arguments. You say `papp` is a very bad name. If I were to counter by saying `papp` is a very good name, we have both effectively said nothing at all :)

I chose `papp` because 1. it's short for "partial application", and 2. it's **short**. You kind of lose the brevity benefits with a longer name such as `partialLeft`:

```js
var addTen = add.partialLeft(10) // <-- long!
var addTen = add.bind(null, 10)
var addTen = (y) => add(10, y)
var addTen = add.papp(10)
```

Other languages such as Haskell and Elm don't have this problem because their functions are curried by default. But alas, we have JavaScript.

P.S. `partialRight` is related to #2

**Comment by Alexsey** [comment]
I'm also sure that what ever name it would be it Must be short. Other way it's not better than rewriting with arrow function. Why `Lodash` and `Ramda` has such? Because those where taken before ES6 came out

**Comment by kevinSuttle** [comment]
Thanks for the thorough explanations!
